# 01 — Analisi Preliminare

Notebook dedicato al caricamento del dataset, pulizia delle colonne e prima analisi esplorativa.

**Sprint 1 | Settimana 1**

In [1]:
# Librerie principali
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Impostazioni grafici
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 5)

print("Librerie importate correttamente")

Librerie importate correttamente

## US-01 · Caricamento e Prima Ispezione del Dataset

In [13]:
from datasets import load_dataset
import pandas as pd

dataset = load_dataset("aai510-group1/telco-customer-churn")

# Salva il dataset completo in data/raw/
df.to_csv("/Users/antoniohopee/Desktop/projects/telco-churn-ml/data/raw/telco_churn.csv", index=False)
print("Dataset salvato correttamente")

df = pd.concat([
    dataset['train'].to_pandas(),
    dataset['validation'].to_pandas(),
    dataset['test'].to_pandas()
], ignore_index=True)

print(df.shape)  # (7043, 52)

Dataset salvato correttamente
(7043, 52)

In [ ]:
# Verifica dimensioni
print(f"Righe: {df.shape[0]}")
print(f"Colonne: {df.shape[1]}")

# Tipi di dato per ogni colonna
print("\nTipi di dato:")
print(df.dtypes)

Righe: 7043
Colonne: 52

Tipi di dato:
Age                                    int64
Avg Monthly GB Download                int64
Avg Monthly Long Distance Charges    float64
Churn                                  int64
Churn Category                           str
Churn Reason                             str
Churn Score                            int64
City                                     str
CLTV                                   int64
Contract                                 str
Country                                  str
Customer ID                              str
Customer Status                          str
Dependents                             int64
Device Protection Plan                 int64
Gender                                   str
Internet Service                       int64
Internet Type                            str
Lat Long                                 str
Latitude                             float64
Longitude                            float64
Married                                int64
Monthly Charge                       float64
Multiple Lines                         int64
Number of Dependents                   int64
Number of Referrals                    int64
Offer                                    str
Online Backup                          int64
Online Security                        int64
Paperless Billing                      int64
Partner                                int64
Payment Method                           str
Phone Service                          int64
Population                             int64
Premium Tech Support                   int64
Quarter                                  str
Referred a Friend                      int64
Satisfaction Score                     int64
Senior Citizen                         int64
State                                    str
Streaming Movies                       int64
Streaming Music                        int64
Streaming TV                           int64
Tenure in Months                       int64
Total Charges                        float64
Total Extra Data Charges               int64
Total Long Distance Charges          float64
Total Refunds                        float64
Total Revenue                        float64
Under 30                               int64
Unlimited Data                         int64
Zip Code                                 str
dtype: object

In [14]:
# Prime 5 righe
print("Prime 5 righe:")
df.head()

Prime 5 righe:

,Age,Avg Monthly GB Download,Avg Monthly Long Distance Charges,Churn,Churn Category,Churn Reason,Churn Score,City,CLTV,Contract,...,Streaming TV,Tenure in Months,Total Charges,Total Extra Data Charges,Total Long Distance Charges,Total Refunds,Total Revenue,Under 30,Unlimited Data,Zip Code
0,72,4,19.44,0,NaN,NaN,51,San Mateo,4849,Two Year,...,0,25,2191.15,0,486.00,0.0,2677.15,0,1,94403
1,27,59,45.62,0,NaN,NaN,27,Sutter Creek,3715,Month-to-Month,...,1,35,3418.20,0,1596.70,0.0,5014.90,1,1,95685
2,59,0,16.07,0,NaN,NaN,59,Santa Cruz,5092,Month-to-Month,...,0,46,851.20,0,739.22,0.0,1590.42,0,0,95064
3,25,27,0.00,0,NaN,NaN,49,Brea,2068,One Year,...,0,27,1246.40,30,0.00,0.0,1276.40,1,0,92823
4,31,21,17.22,1,Dissatisfaction,Network reliability,88,San Jose,4026,One Year,...,0,58,3563.80,0,998.76,0.0,4562.56,0,1,95117

In [17]:
df.tail()

,Age,Avg Monthly GB Download,Avg Monthly Long Distance Charges,Churn,Churn Category,Churn Reason,Churn Score,City,CLTV,Contract,...,Streaming TV,Tenure in Months,Total Charges,Total Extra Data Charges,Total Long Distance Charges,Total Refunds,Total Revenue,Under 30,Unlimited Data,Zip Code
7038,33,12,10.67,0,NaN,NaN,53,Clayton,4847,Month-to-Month,...,1,29,2878.75,0,309.43,0.0,3188.18,0,1,94517
7039,36,30,30.44,0,NaN,NaN,45,Nicolaus,5470,Two Year,...,1,59,5655.45,0,1795.96,0.0,7451.41,0,1,95659
7040,57,24,4.51,0,NaN,NaN,74,Walnut Creek,4471,Two Year,...,1,61,5175.30,0,275.11,0.0,5450.41,0,1,94596
7041,35,24,47.06,0,NaN,NaN,70,Valyermo,5445,Two Year,...,0,30,1653.85,0,1411.80,0.0,3065.65,0,1,93563
7042,54,24,12.85,0,NaN,NaN,70,Rancho Cucamonga,5065,Two Year,...,1,72,7998.80,70,925.20,0.0,8994.00,0,0,91701

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 52 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                7043 non-null   int64
 1   Avg Monthly GB Download            7043 non-null   int64
 2   Avg Monthly Long Distance Charges  7043 non-null   float64
 3   Churn                              7043 non-null   int64
 4   Churn Category                     1869 non-null   str
 5   Churn Reason                       1869 non-null   str
 6   Churn Score                        7043 non-null   int64
 7   City                               7043 non-null   str
 8   CLTV                               7043 non-null   int64
 9   Contract                           7043 non-null   str
 10  Country                            7043 non-null   str
 11  Customer ID                        7043 non-null   str
 12  Customer Status                    7043 non-null   str
 13  Dependents                         7043 non-null   int64
 14  Device Protection Plan             7043 non-null   int64
 15  Gender                             7043 non-null   str
 16  Internet Service                   7043 non-null   int64
 17  Internet Type                      5517 non-null   str
 18  Lat Long                           7043 non-null   str
 19  Latitude                           7043 non-null   float64
 20  Longitude                          7043 non-null   float64
 21  Married                            7043 non-null   int64
 22  Monthly Charge                     7043 non-null   float64
 23  Multiple Lines                     7043 non-null   int64
 24  Number of Dependents               7043 non-null   int64
 25  Number of Referrals                7043 non-null   int64
 26  Offer                              3166 non-null   str
 27  Online Backup                      7043 non-null   int64
 28  Online Security                    7043 non-null   int64
 29  Paperless Billing                  7043 non-null   int64
 30  Partner                            7043 non-null   int64
 31  Payment Method                     7043 non-null   str
 32  Phone Service                      7043 non-null   int64
 33  Population                         7043 non-null   int64
 34  Premium Tech Support               7043 non-null   int64
 35  Quarter                            7043 non-null   str
 36  Referred a Friend                  7043 non-null   int64
 37  Satisfaction Score                 7043 non-null   int64
 38  Senior Citizen                     7043 non-null   int64
 39  State                              7043 non-null   str
 40  Streaming Movies                   7043 non-null   int64
 41  Streaming Music                    7043 non-null   int64
 42  Streaming TV                       7043 non-null   int64
 43  Tenure in Months                   7043 non-null   int64
 44  Total Charges                      7043 non-null   float64
 45  Total Extra Data Charges           7043 non-null   int64
 46  Total Long Distance Charges        7043 non-null   float64
 47  Total Refunds                      7043 non-null   float64
 48  Total Revenue                      7043 non-null   float64
 49  Under 30                           7043 non-null   int64
 50  Unlimited Data                     7043 non-null   int64
 51  Zip Code                           7043 non-null   str
dtypes: float64(8), int64(29), str(15)
memory usage: 3.6 MB